#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-linux-androideabi-gcc -DOPENSSL_THREADS -D_REENTRANT -DL_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall --sysroot=/home/novarow/tools/android-4-tc/sysroot -DANDROID -DDECLARE_TIMEZONE -Wall -I/home/novarow/tools/android-4-tc/arm-linux-androideabi/include -O3 -fomit-frame-pointer"
  #define PLATFORM "linux-generic32"
  #define DATE "Thu Jul  5 16:19:54 CEST 2012"
#endif
